-- LEFT JOIN + NULL LOGIC PRACTICE

-- 1) Find all customers who never made a payment.
-- Show customer basic info.
SELECT c.


-- 2) Find all customers who never rented any film.
-- Show customer basic info.



-- 3) Show every customer together with how many payments they made.
-- Customers with no payments must still appear.



-- 4) Show every customer together with their total amount paid.
-- Customers with no payments must still appear.



-- 5) Find all films that were never added to inventory.
-- Show film info.



-- 6) Find all films that exist in inventory but were never rented.
-- Show film info.



-- 7) Show every film together with how many times it was rented.
-- Films with zero rentals must still appear.



-- 8) Show every category together with how many films belong to it.
-- Categories with zero films must still appear.



-- 9) Show every language together with how many films use that language.
-- Languages with zero films must still appear.



-- 10) Find all customers who rented films but never made any payment.
-- Return only such customers.



-- 11) Show every staff member together with how many payments they handled.
-- Staff with zero payments must still appear.



-- 12) Show every store together with how many customers belong to it.
-- Stores with zero customers must still appear.



-- 13) Show every store together with how many staff members work there.
-- Stores with zero staff must still appear.



-- 14) Find all customers who have no payment greater than 8.
-- Keep customers with no payments at all, too.



-- 15) Show every customer together with the number of payments above 8.
-- Customers with none should still appear with 0.



-- 16) Find all films that were never rented, even though they are present in inventory.
-- Return film title and inventory-related identifiers if useful.



-- 17) Show every customer together with their most recent payment date.
-- Customers with no payments must still appear.



-- 18) Show every customer together with their first rental date.
-- Customers with no rentals must still appear.



-- 19) Find all categories for which no film from that category was ever rented.
-- Return category info.



-- 20) Show every category together with the number of distinct rented films in it.
-- Categories with zero rented films must still appear.



-- 21) Show every film together with total revenue generated by that film.
-- Films with no revenue must still appear.



-- 22) Find all customers who made payments but never rented anything.
-- Return only such customers.



-- 23) Show every customer together with a flag:
-- 'has_payments' / 'no_payments'



-- 24) Show every film together with a flag:
-- 'rented' / 'never_rented'



-- 25) Show every customer together with:
-- number of rentals,
-- number of payments,
-- and keep customers even if one or both counts are zero.